// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAQdoVxwE_HwsE7L56VQMhrKnFmye-A5A',
    appId: '1:176515573412:web:65cf2e1b8f8a7ef107a831',
    messagingSenderId: '176515573412',
    projectId: 'tijaabo-3b05d',
    authDomain: 'tijaabo-3b05d.firebaseapp.com',
    storageBucket: 'tijaabo-3b05d.appspot.com',
    measurementId: 'G-P153ZD3H3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC000MEXzj8OusU3qo9Sg0kRSkmZZBK_w',
    appId: '1:176515573412:android:f08a785e4f33d67607a831',
    messagingSenderId: '176515573412',
    projectId: 'tijaabo-3b05d',
    storageBucket: 'tijaabo-3b05d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbUkzo2N8-rB-3pBJJ56HMdH2CbkhNH3I',
    appId: '1:176515573412:ios:2b4cd3404920360907a831',
    messagingSenderId: '176515573412',
    projectId: 'tijaabo-3b05d',
    storageBucket: 'tijaabo-3b05d.appspot.com',
    iosClientId: '176515573412-7tm8ok8kpmje2sapgavb9m3jvkeu3pcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbUkzo2N8-rB-3pBJJ56HMdH2CbkhNH3I',
    appId: '1:176515573412:ios:2b4cd3404920360907a831',
    messagingSenderId: '176515573412',
    projectId: 'tijaabo-3b05d',
    storageBucket: 'tijaabo-3b05d.appspot.com',
    iosClientId: '176515573412-7tm8ok8kpmje2sapgavb9m3jvkeu3pcg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
